name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff pre-commit
      - name: Run linter (ruff) and fail on issues
        run: |
          ruff check .
      - name: Run pre-commit (checks)
        run: |
          pre-commit run --all-files
      - name: Run tests
        run: |
          pytest -q
